---
title: How to Write a Research Paper Using Google Docs
colorlinks : true
author:
  - Ramesh Govindan
abstract: Google Docs is convenient because it permits collaborative editing. This is great for papers, because it provides ways for others to suggest edits, as well as to track to-do items left as comments. However, it is hard to use Google Doc for papers because of all the formatting restrictions imposed by conferences, and the rigid formatting that one has to do.
---
